In [1]:
# Create csv with measures (Nutzungen) from pdf

In [1]:
import os
import h5py
import cv2
import numpy as np
import pandas as pd
import sklearn as skl
from matplotlib import pyplot as plt

from pdf2image import convert_from_path, convert_from_bytes
import pytesseract

from OCRPage import OCRPage
from OCRPharse import OCRPharse

In [2]:
# set home directory
home_path = os.getcwd()[:os.getcwd().find('Code/python/obf_autax/ocr')-1]
# set input_path
input_path = os.path.join(home_path, 'Data', 'obf_autman', 'pdf', 'Manuale_Pernitz_PS.pdf')
# Operat Hinterriß
# Manuale_Pernitz_PS
# 171_11_GS_Mannersdorf
# 171_12_PS_Pernitz

In [3]:
# convert pdf to image (pdf2image)
def convert_to_image(input_path, page_nr):

    pages = convert_from_path(input_path, 500, first_page=page_nr, last_page=page_nr)

    return pages[0]

In [4]:
#img = convert_to_image(input_path, 3).convert('RGB')
#img = np.array(img)
# 113

img = convert_to_image(input_path, 144).convert('RGB')
img = np.array(img)
ocr = OCRPage(img)
ocr.convert()

In [5]:
phr = OCRPharse(ocr)

# 
dic_ma = {'S':0, 'MA':1, 'FL':0, 'LH':1, 'NH':1, 'SUM':0, 'DR':1, 'BH':1, 'ZP':1, 'SG':1, 'RU':1}
phr.set_mass_struc(dic_ma)

In [6]:
phr.get_abt()

'207E1'

298
299
300 miss d1 d2, g1 g2 g3 m0
301 g l i k l
307 a1 a2 b0 d0
312 l m
313
315
316
317
318
319
320
321

In [8]:
# structure of measure (Nutzungszeile)
# S...Schicht, MA...Maßnahme, LH...Efm LH, NH...Efm NH, SUM...Sum, 
# DR...Dringlichkeit, BH...Behörde, ZP...Zeitpunkt, SG...Schlägerung, RU:1
dic_ma = {'S':0, 'MA':1, 'FL':0, 'LH':1, 'NH':1, 'SUM':0, 'DR':1, 'BH':1, 'ZP':1, 'SG':1, 'RU':1}
mass = []

for i in range(2,404): #130,829
    img = convert_to_image(input_path, i).convert('RGB')
    img = np.array(img)
    ocr = OCRPage(img)
    ocr.convert()
    
    phr = OCRPharse(ocr)
    phr.set_mass_struc(dic_ma)
    
    abt = phr.get_abt()
    ma = phr.get_mass()
    
    if ma:
        for m in ma:
            m['ABT'] = abt
            mass.append(m)
    print(abt)

201A0
201B1
DF
Mi
['DF1070213636', 'Mitte Dezennium, bei Bundesstraße']
0 nutz
1 text
201B2
DF
Mi
['DF0702136%36', 'Mitte - Ende Dezennium']
0 nutz
exception
201B3
201B4
201B5
201C1
DE
En
['DE400213190', 'Ende Dezennium']
0 nutz
1 text
201C2
201D1
201D2
201E1
DF
An
['DF540113190', 'Anfang Dezennium, Oberhang, Süd-Teil']
0 nutz
1 text
201E2
201E3
201E4
201E5
DF
An
['DF6010113523', 'Anfang - Mitte Dezennium, im Nord-Teil, AH fördern, und Südteil KI fördern']
0 nutz
1 text
201F0
DF
An
['DF3040113435', 'Anfang - Mitte Dezennium, meist flach']
0 nutz
1 text
201H1
201H2
201H3
201I1
201I2
201J0
202A1
202A2
202B1
DF
An
['DF540113190', 'Anfang - Mitte Dezennium, im Südwest-Teil']
0 nutz
1 text
202B2
202C1
DF
An
['DF0501131%90', 'Anfang - Mitte Dezennium, im Südwest-Teil']
0 nutz
exception
202C2
202D1
DF
An
['DF050113190', 'Anfang - Mitte Dezennium, im Südwest-Teil']
0 nutz
1 text
202D2
202D3
DE

An

DF

An
['DE070113523', '', 'Anfang Dezennium, Nordost-Teil (Untergang)', '', 'DF040113190', '', 

212G3
212G4
RM
Mi
['RM100200213135', 'Mitte Dezennium, Verjüngung schonen']
0 nutz
1 text
212H0
RM
En
['RM25050213135', 'Ende Dezennium']
0 nutz
1 text
212I1
DE
An
['DE080113435', 'Anfang Dezennium']
0 nutz
1 text
212I2
212I3
212I4
212J1
DE
An
['DE070113435', 'Anfang Dezennium']
0 nutz
1 text
212J2
212J3
212L1
DF
An
['DF080113435', 'Anfang - Mitte Dezennium']
0 nutz
1 text
212L2
DF
En
['DF075213636', 'Ende Dezennium']
0 nutz
1 text
213A1
DE
Te
['DEL134>53', 'Te']
0 nutz
exception
213A2


/home/philipp/miniconda3/envs/autax_rec/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/philipp/miniconda3/envs/autax_rec/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


213B1
213B2
DF
An
['DF080113636', 'Anfang Dezennium, im Norden']
0 nutz
1 text
213B3
213B4
DE
An
['DE080113435', 'Anfang Dezennium, LA fördern']
0 nutz
1 text
213C1
213C2
DF
Mi
['DF4040213435', 'Mitte Dezennium']
0 nutz
1 text
213D1
213D2
DE
En
['DE060213435', 'Ende Dezennium, im Osten, LA fördern']
0 nutz
1 text
213D3
RM
Mi
['RM4000213135', 'Mitte - Ende Dezennium']
0 nutz
1 text
213E1
DE
An
['DE070113435', 'Anfang Dezennium']
0 nutz
1 text
213E2
213E3
213F1
DE
En
['DE060213435', 'Ende Dezennium, im Osten, LA fördern']
0 nutz
1 text
213F2
213F3
213G0
5
['5']
0 text
213J0
214A1
214A2
214B1
214B2
214C1
214C2
214C3
214D1
214D2
214E0
ZV
['ZV070113130']
0 text
214F1
DF
An
['DF080113435', 'Anfang Dezennium, LA fördern']
0 nutz
1 text
214F2
214G0
214H0
RM
En
['RM05002131%35', 'Ende Dezennium, im Nordosten']
0 nutz
exception
214I1
214I2
214I3
214K1
214K2
214L1
214L2
DE
An
['DE065113190', 'Anfang - Mitte Dezennium, oder späte DP']
0 nutz
1 text
214M0
214N1
214N2
214O0
214P0
214Q0
215A0
215B1
D

In [9]:
mass

[{'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '10',
  'NH': '70',
  'SUM': 0,
  'DR': '2',
  'BH': '1',
  'ZP': '3',
  'SG': '6',
  'RU': '36',
  'Text': 'Mitte Dezennium, bei Bundesstraße',
  'ABT': '201B2'},
 {'S': 0,
  'MA': 'DE',
  'FL': 0,
  'LH': '40',
  'NH': '0',
  'SUM': 0,
  'DR': '2',
  'BH': '1',
  'ZP': '3',
  'SG': '1',
  'RU': '90',
  'Text': 'Ende Dezennium',
  'ABT': '201C2'},
 {'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '5',
  'NH': '40',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '1',
  'RU': '90',
  'Text': 'Anfang Dezennium, Oberhang, Süd-Teil',
  'ABT': '201E2'},
 {'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '60',
  'NH': '10',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '5',
  'RU': '23',
  'Text': 'Anfang - Mitte Dezennium, im Nord-Teil, AH fördern, und Südteil KI fördern',
  'ABT': '201F0'},
 {'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '30',
  'NH': '40',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '4',
  'RU': '35',
  'Text'

In [10]:
mass_pd = pd.DataFrame.from_dict(mass)

In [11]:
data_path = os.path.join(home_path, 'Data', 'obf_autman','csv')
mass_pd.to_csv(data_path + "/nutzungen_171_12_20200818.csv", index=False)

## Text

In [8]:
# get text
txt = ocr.get_text('text')

In [9]:
# split lines
txt = txt.splitlines()

In [10]:
txt

['ST im SüdWesten eben, im SüdOsten Graben, im Graben vernässt mit STOE 05 .',
 'BE einige BU KB RU ERASES AH FI, an "F1" zahlreich AS, LA im NordOsten, einige eingewachsene BU-El-Überhälter, im Norden örtlich jünger, schöne Schaftformen, ungleichmäßig, ungleichaltrig teils 10 Jahre älter, Hasel, mäßig vergrast und verkrautet']

In [11]:
txt[1].replace('El', 'EI')
txt[1].replace('Kl', 'KI')
txt[1].replace('Zl', 'ZI')

'BE einige BU KB RU ERASES AH FI, an "F1" zahlreich AS, LA im NordOsten, einige eingewachsene BU-El-Überhälter, im Norden örtlich jünger, schöne Schaftformen, ungleichmäßig, ungleichaltrig teils 10 Jahre älter, Hasel, mäßig vergrast und verkrautet'

In [17]:
txt

['ST steilerer Abfall zu "BO", am Rücken blockig, BE einzelne SK, BU im NordOsten, ungleichaltrig +/- 20 Jahre, geringe',
 'Qualität, meist krummwüchsig, mäßig vergrast und verkrautet']

In [18]:
len(txt)

2

In [61]:
for i in range(3-2):
    txt.append("")

In [62]:
l0, l1, l2 = txt

In [7]:
img = convert_to_image(input_path, 158).convert('RGB')
img = np.array(img)
ocr = OCRPage(img)
ocr.convert()

## Maßnahme

In [8]:
ma = ocr.get_text('mass')
#spaces = ocr.get_spaces()

In [21]:
# ph 
dic_ma = {'S':0, 'MA':1, 'FL':0, 'LH':1, 'NH':1, 'SUM':0, 'DR':1, 'BH':1, 'ZP':1, 'SG':1, 'RU':1}
# gernot
#dic_ma = {'S':0, 'MA':1, 'FL':1, 'LH':1, 'NH':1, 'SUM':0, 'DR':1, 'BH':0, 'ZP':1, 'SG':1, 'RU':1}

In [22]:
ma

'DE0 75113636\nAnfang - Mitte Dezennium, Gelände ungleichmäßig'

In [23]:
# 1
def split_lines(ma, dic_ma):
    ma = ma.splitlines()
    row_info = []
    for i in range(len(ma)):
        if ma[i][dic_ma['S']:dic_ma['S']+2] in ["DE", "DF", "RM", "LI", "AD", "KH"]:
            ma[i] = ma[i].replace(" ", "")
            ma[i] = ma[i].replace(",", "")
            ma[i] = ma[i].replace("O", "")
            row_info.append("nutz")
        else:
            ma[i] = ma[i].replace("Bl", "BI")
            ma[i] = ma[i].replace("El", "EI")
            ma[i] = ma[i].replace("Kl", "KI")
            ma[i] = ma[i].replace("Ll", "LI")
            ma[i] = ma[i].replace("Zl", "ZI")
            row_info.append("text")
        
    return ma, row_info

In [24]:
#
def otsu(gray):
    '''
        otsu algorithm for finding the best threshold value
    '''
    pixel_number = gray.shape[0]
    mean_weigth = 1.0/pixel_number
    his, bins = np.histogram(gray, np.array(range(0, np.max(gray)+1)))
    final_thresh = -1
    final_value = -1
    for t in bins[1:-1]: # This goes from 1 to 254 uint8 range (Pretty sure wont be those values)
        Wb = np.sum(his[:t]) * mean_weigth
        Wf = np.sum(his[t:]) * mean_weigth

        mub = np.mean(his[:t])
        muf = np.mean(his[t:])

        value = Wb * Wf * (mub - muf) ** 2

        if value > final_value:
            final_thresh = t
            final_value = value

    return(final_thresh)

In [25]:
def find_row_corrdinates(rows_pos):
    rows = []
    temp = []
    x = rows_pos[0]
    for cor in rows_pos:
        if (cor < x * 1.1) & (cor > x * 0.9):
            temp.append(cor)
        else:
            rows.append(int(sum(temp) / len(temp)))
            x = cor
            temp = []
    rows.append(int(sum(temp) / len(temp)))
    return(np.array(rows))

In [26]:
# OCRPage
def get_char_positions(img_thresh):
    # invert binary
    img = cv2.bitwise_not(img_thresh)
    # cut the mass
    img = ocr.cut_feature(img, "mass")
    # get boundries of detected characters
    rects = ocr.find_objects(img)
    # convert to numpy array
    rects = np.asarray(rects)
    
    # filter small points
    rect_max_hight = rects[:,3].max()
    rec_fil = rects[rect_max_hight/rects[:,3] < rect_max_hight/(rects[:,3].min()*1.5)]
    # get lower coordinates
    rec_fil[:,1] = rec_fil[:,1] + rec_fil[:,3]
    # get unique row positions
    rows_pos = np.sort(np.unique(rec_fil[:,1]))
    # filter noise
    rows_pos = find_row_corrdinates(rows_pos)
    
    return(rec_fil,rows_pos)

In [27]:
data, info = split_lines(ma, dic_ma)

In [28]:
rec_fil,rows_pos = get_char_positions(ocr.img_thresh)

In [29]:
rec_fil

array([[1125,  324,    9,   21],
       [1984,  312,    8,   43],
       [1711,  312,    8,   43],
       [ 988,  312,    8,   43],
       [ 567,  312,    8,   43],
       [2000,  330,   39,   62],
       [1597,  330,   39,   62],
       [1507,  313,   35,   45],
       [1007,  313,   35,   45],
       [ 805,  312,   37,   44],
       [ 374,  330,   39,   62],
       [1885,  313,   42,   46],
       [1818,  312,   59,   45],
       [1727,  313,   38,   46],
       [1663,  314,   40,   47],
       [1554,  312,   36,   45],
       [1436,  314,   40,   47],
       [1345,  312,   36,   45],
       [1297,  313,   42,   46],
       [1232,  314,   40,   47],
       [1053,  312,   59,   45],
       [ 942,  312,   36,   45],
       [ 896,  312,   36,   45],
       [ 847,  314,   40,   47],
       [ 759,  314,   40,   47],
       [ 630,  314,   40,   47],
       [ 331,  312,   36,   45],
       [ 282,  313,   42,   46],
       [ 215,  312,   36,   45],
       [ 605,  313,   20,   57],
       [ 5

In [30]:
rows_pos

array([217, 320])

In [31]:
# set index of nutz
idx = 0
# filter only nutzungs row
rec_fil_fil = rec_fil[np.where((rec_fil[:,1] <= rows_pos[idx]*1.05) & (rec_fil[:,1] >= rows_pos[idx]*0.95))]
data_nutz = data[idx]



In [32]:
data_nutz

'DE075113636'

In [33]:
rec_fil_fil

array([[412, 218,  40,  59],
       [366, 216,  41,  57],
       [759, 218,  41,  60],
       [620, 218,  41,  60],
       [556, 216,  22,  58],
       [487, 216,  22,  58],
       [296, 218,  40,  60],
       [806, 218,  40,  61],
       [690, 218,  40,  61],
       [222, 216,  44,  60],
       [161, 216,  49,  60]])

In [34]:
rec_fil_fil[np.where(rec_fil_fil[:,3] > rec_max_hight/2)]

NameError: name 'rec_max_hight' is not defined

In [35]:
rec = rec_fil_fil
len_1 = dic_ma['S'] + dic_ma['MA']*2
len_2 = dic_ma['DR'] + dic_ma['BH'] + dic_ma['ZP'] + dic_ma['SG'] + dic_ma['RU']*2
    
# sort
rec.view('i8,i8,i8,i8').sort(order=['f0'], axis=0)

In [36]:
rec

array([[161, 216,  49,  60],
       [222, 216,  44,  60],
       [296, 218,  40,  60],
       [366, 216,  41,  57],
       [412, 218,  40,  59],
       [487, 216,  22,  58],
       [556, 216,  22,  58],
       [620, 218,  41,  60],
       [690, 218,  40,  61],
       [759, 218,  41,  60],
       [806, 218,  40,  61]])

In [37]:
rec_max_hight = rec[:,3].max()
#rec_fil = rects[rect_max_hight/rects[:,3] < rect_max_hight/(rects[:,3].min()*1.5)]

In [38]:
result = np.where((rec[:,2] < rec_max_hight/2.8) & (rec[:,2] > rec_max_hight/3.2))

In [39]:
rec[:,3]

array([60, 60, 60, 57, 59, 58, 58, 60, 61, 60, 61])

In [40]:
result[0]

array([], dtype=int64)

In [41]:
for i in result[0]:
    print(i)

In [42]:
if result:
    print('yes')

yes


In [43]:
result[0].siz

AttributeError: 'numpy.ndarray' object has no attribute 'siz'

In [44]:
if 2 in get_comma(rec):
    print('yes')

NameError: name 'get_comma' is not defined

In [45]:
get_comma(rec)-2

NameError: name 'get_comma' is not defined

In [46]:
def get_comma(rec):
    rec.view('i8,i8,i8,i8').sort(order=['f0'], axis=0)
    idx = np.where((rec[:,3] < rec_max_hight/2.8) & (rec[:,3] > rec_max_hight/3.2))
    return idx[0]

In [47]:
def get_dist_char(data, dic_ma, rec, rows_pos, info):
    '''
    get distances between characters
    dic_ma = {'S':0, 'MA':1, 'FL':1, 'LH':1, 'NH':1, 'SUM':0, 'DR':1, 'BH':0, 'ZP':1, 'SG':1, 'RU':1}
    string = 'DF13,8700023435'
    '''
    distances = []
    ### get info about structure
    len_1 = dic_ma['S'] + dic_ma['MA']*2
    len_2 = dic_ma['DR'] + dic_ma['BH'] + dic_ma['ZP'] + dic_ma['SG'] + dic_ma['RU']*2
    
    #for i, line in enumerate(data):
        # filter only nutzungs row
        #if info[i] == 'nutz':
            #rec = rec_fil[np.where(rec_fil[:,1] == rows_pos[i])]

    # sort
    rec.view('i8,i8,i8,i8').sort(order=['f0'], axis=0)
    
    rec_max_hight = rec[:,3].max()
    
    # get comma
    idx_comma = np.where((rec[:,3] < rec_max_hight/2.8) & (rec[:,3] > rec_max_hight/3.2))[0] - len_1 - 1
    
    rec = rec[np.where(rec[:,3] > rec_max_hight/2)]

    # filter just relevant 
    rec = rec[len_1:-len_2]

    width_m = np.median(rec[:,2,])
    pos_x = rec[:,0,].copy()
    dist = pos_x[1:] - (pos_x[:-1]+int(width_m))

    thresh = otsu(dist)

    thisdict = {"dist": dist, "thresh": thresh}
    distances.append(thisdict)
            
    return distances, idx_comma

In [48]:
def pharse_string(string, dist, thresh_val, idx_comma):
    '''
    pharse string into usable variables based on the distance between the characters
    input:  string = '13,87000'
            dist = np.array([ 5, 17, 19,  7,  6, 20])
    output: mass = ['13,8', '700', '0']
    '''
    # list of variables
    mass = []
    # if comma is detected swich to 1
    comma = 0
    # temporary helper variable
    save = string[0]
    # loop over char in string
    for i, char in enumerate(string[1:]):
        # if char is comma -> add char and reuse dist on ith position
        if i in idx_comma:
            save = save + ',' + char
            dist[i] = 0
            comma += 1
        # check if current dist is bigger than threshold -> add to list of variables
        else:
            if dist[i] <= thresh_val:
                save = save + char
            else:
                mass.append(save)
                save = char
    # add last variable
    mass.append(save)
    
    return mass

In [49]:
def from_string(ma_as_str, dic_ma, distances, idx_comma):
    # TYP
    # first 2 -> Maßnahme
    # last 6 -> Nutzcode
    
    dic_ = {'S':0, 'MA':0, 'FL':0, 'LH':0, 'NH':0, 'SUM':0, 'DR':0, 'BH':0, 'ZP':0, 'SG':0, 'RU':0}
    
    #len_tech = dic_ma['DR'] + dic_ma['BH'] + dic_ma['ZP'] + dic_ma['SG'] + dic_ma['RU']*2
    
    # set Schicht (S)
    if dic_ma['S']:
        dic_['S'] = ma_as_str[:dic_ma['S']]
        
    # set Maßnahme (MA)
    if dic_ma['MA']:
        dic_['MA'] = ma_as_str[dic_ma['S']:dic_ma['S']+2]
    
    pos = 0
    
    # set Rückung (RU)
    if dic_ma['RU']:
        pos = -2
        dic_['RU'] = ma_as_str[pos:]
        
    # set Schlägerung (SG), Zeitpunkt (ZP), Behörde (BH), Dringlichkeit (DR)
    for i in ['SG', 'ZP', 'BH', 'DR']:
        if dic_ma[i]:
            pos -= 1
            dic_[i] = ma_as_str[pos:pos+1]
            
    #print(ma_as_str[dic_ma['S']+2:pos])
    #print(distances["dist"])
    
    # pharse FL - LH - NH string
    data_ma = pharse_string(ma_as_str[dic_ma['S']+2:pos], distances["dist"], distances["thresh"],idx_comma)
    print(data_ma)
    
    # set Fläche (FL), Laubholz (LH), Nadelholz (NH), Summe (SUM)
    cur = 0
    for typ in ['FL', 'LH', 'NH', 'SUM']:
        if dic_ma[typ]:
            dic_[typ] = data_ma[cur]
            cur += 1 
    
    return dic_

In [50]:
data, info = split_lines(ma, dic_ma)

print(data, info)

rec_fil,rows_pos = get_char_positions(ocr.img_thresh)

print(rows_pos)

# set index of nutz
idx = 0
# filter only nutzungs row
rec_fil_fil = rec_fil[np.where((rec_fil[:,1] <= rows_pos[idx]*1.05) & (rec_fil[:,1] >= rows_pos[idx]*0.95))]
data_nutz = data[idx]
distances, idx_comma = get_dist_char(data, dic_ma, rec_fil_fil, rows_pos[idx], info)

print(distances, idx_comma)

print(data[0])
print(dic_ma)
z = from_string(data[0], dic_ma, distances[0], idx_comma)
z

['DE075113636', 'Anfang - Mitte Dezennium, Gelände ungleichmäßig'] ['nutz', 'text']
[217 320]
[{'dist': array([30,  6]), 'thresh': 29}] []
DE075113636
{'S': 0, 'MA': 1, 'FL': 0, 'LH': 1, 'NH': 1, 'SUM': 0, 'DR': 1, 'BH': 1, 'ZP': 1, 'SG': 1, 'RU': 1}
['0', '75']


{'S': 0,
 'MA': 'DE',
 'FL': 0,
 'LH': '0',
 'NH': '75',
 'SUM': 0,
 'DR': '1',
 'BH': '1',
 'ZP': '3',
 'SG': '6',
 'RU': '36'}

In [106]:
nutzungen = []

for i in range(2, 10):
    
    img = convert_to_image(input_path, i).convert('RGB')
    img = np.array(img)
    ocr = OCRPage(img)
    ocr.convert()

    ma = ocr.get_text('mass')
    
    if  ma != '':
        data, info = split_lines(ma, dic_ma)
        
        print('---------------------------------------------')
        print(data, info)

        rec_fil,rows_pos = get_char_positions(ocr.img_thresh)

        print(rows_pos)

        # set index of nutz
        idx = 0
        # filter only nutzungs row
        rec_fil_fil = rec_fil[np.where((rec_fil[:,1] <= rows_pos[idx]*1.05) & (rec_fil[:,1] >= rows_pos[idx]*0.95))]
        data_nutz = data[idx]
        distances, idx_comma = get_dist_char(data, dic_ma, rec_fil_fil, rows_pos[idx], info)

        print(distances)

        z = from_string(data[0], dic_ma, distances[0], idx_comma)
        nutzungen.append(z)
        print(z)

---------------------------------------------
['DF68500013435', 'EI fördern u freistellen'] ['nutz', 'text']
[464 545]
[{'dist': array([22, 26,  7,  8, 26]), 'thresh': 25}]
['6,8', '500', '0']
{'S': 0, 'MA': 'DF', 'FL': '6,8', 'LH': '500', 'NH': '0', 'SUM': 0, 'DR': '1', 'BH': 0, 'ZP': '3', 'SG': '4', 'RU': '35'}
---------------------------------------------
['DF160023435', 'EI u Edel-LH fördern u freistellen'] ['nutz', 'text']
[523 607]
[{'dist': array([24,  8, 25]), 'thresh': 24}]
['160', '0']


IndexError: list index out of range

In [42]:
nutzungen

[{'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '0',
  'NH': '90',
  'SUM': 0,
  'DR': '2',
  'BH': '1',
  'ZP': '3',
  'SG': '4',
  'RU': '35'},
 {'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '0',
  'NH': '80',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '4',
  'RU': '35'},
 {'S': 0,
  'MA': 'RM',
  'FL': 0,
  'LH': '200',
  'NH': '200',
  'SUM': 0,
  'DR': '2',
  'BH': '3',
  'ZP': '3',
  'SG': '1',
  'RU': '35'},
 {'S': 0,
  'MA': 'DE',
  'FL': 0,
  'LH': '0',
  'NH': '75',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '4',
  'RU': '35'},
 {'S': 0,
  'MA': 'DF',
  'FL': 0,
  'LH': '0',
  'NH': '90',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '4',
  'RU': '35'},
 {'S': 0,
  'MA': 'DE',
  'FL': 0,
  'LH': '0',
  'NH': '75',
  'SUM': 0,
  'DR': '1',
  'BH': '1',
  'ZP': '3',
  'SG': '6',
  'RU': '36'}]

In [43]:
pd.DataFrame(nutzungen)

S  MA  FL   LH   NH  SUM DR BH ZP SG  RU
0  0  DF   0    0   90    0  2  1  3  4  35
1  0  DF   0    0   80    0  1  1  3  4  35
2  0  RM   0  200  200    0  2  3  3  1  35
3  0  DE   0    0   75    0  1  1  3  4  35
4  0  DF   0    0   90    0  1  1  3  4  35
5  0  DE   0    0   75    0  1  1  3  6  36

In [226]:
print(data[0])
print(dic_ma)
z = from_string(data[0], dic_ma, distances[0])
z

DF10700013435
{'S': 0, 'MA': 1, 'FL': 1, 'LH': 1, 'NH': 1, 'SUM': 0, 'DR': 1, 'BH': 0, 'ZP': 1, 'SG': 1, 'RU': 1}


{'S': 0,
 'MA': 'DF',
 'FL': '10',
 'LH': '700',
 'NH': '0',
 'SUM': 0,
 'DR': '1',
 'BH': 0,
 'ZP': '3',
 'SG': '4',
 'RU': '35'}

In [11]:
img_thresh = ocr.img_thresh
rec_fil,rows_pos = get_char_positions(img_thresh)

NameError: name 'get_char_positions' is not defined

In [12]:
info

['nutz', 'text']

In [35]:
distances = get_dist_char(data, dic_ma, rec_fil, rows_pos, info)

ValueError: cannot convert float NaN to integer

In [72]:
def get_dist_char(data, dic_ma, rec, rows_pos, info):
    '''
    get distances between characters
    dic_ma = {'S':0, 'MA':1, 'FL':1, 'LH':1, 'NH':1, 'SUM':0, 'DR':1, 'BH':0, 'ZP':1, 'SG':1, 'RU':1}
    string = 'DF13,8700023435'
    '''
    distances = []
    ### get info about structure
    len_1 = dic_ma['S'] + dic_ma['MA']*2
    len_2 = dic_ma['DR'] + dic_ma['BH'] + dic_ma['ZP'] + dic_ma['SG'] + dic_ma['RU']*2
    
    #for i, line in enumerate(data):
        # filter only nutzungs row
        #if info[i] == 'nutz':
            #rec = rec_fil[np.where(rec_fil[:,1] == rows_pos[i])]

    # sort
    rec.view('i8,i8,i8,i8').sort(order=['f0'], axis=0)

    # filter just relevant 
    rec = rec[len_1:-len_2]

    width_m = np.median(rec[:,2,])
    pos_x = rec[:,0,].copy()
    dist = pos_x[1:] - (pos_x[:-1]+int(width_m))

    thresh = otsu(dist)

    thisdict = {"dist": dist, "thresh": thresh}
    distances.append(thisdict)
            
    return distances

In [107]:
#
def otsu(gray):
    '''
        otsu algorithm for finding the best threshold value
    '''
    pixel_number = gray.shape[0]
    mean_weigth = 1.0/pixel_number
    his, bins = np.histogram(gray, np.array(range(0, np.max(gray)+1)))
    final_thresh = -1
    final_value = -1
    for t in bins[1:-1]: # This goes from 1 to 254 uint8 range (Pretty sure wont be those values)
        Wb = np.sum(his[:t]) * mean_weigth
        Wf = np.sum(his[t:]) * mean_weigth

        mub = np.mean(his[:t])
        muf = np.mean(his[t:])

        value = Wb * Wf * (mub - muf) ** 2

        if value > final_value:
            final_thresh = t
            final_value = value

    return(final_thresh)

In [50]:
def find_row_corrdinates(rows_pos):
    rows = []
    temp = []
    x = rows_pos[0]
    for cor in rows_pos:
        if (cor < x * 1.1) & (cor > x * 0.9):
            temp.append(cor)
        else:
            rows.append(int(sum(temp) / len(temp)))
            x = cor
            temp = []
    rows.append(int(sum(temp) / len(temp)))
    return(np.array(rows))

In [54]:
# OCRPage
def get_char_positions(img_thresh):
    # invert binary
    img = cv2.bitwise_not(img_thresh)
    # cut the mass
    img = ocr.cut_feature(img, "mass")
    # get boundries of detected characters
    rects = ocr.find_objects(img)
    # convert to numpy array
    rects = np.asarray(rects)
    
    # filter small points
    rect_max_hight = rects[:,3].max()
    rec_fil = rects[rect_max_hight/rects[:,3] < rect_max_hight/(rects[:,3].min()*1.5)]
    # get lower coordinates
    rec_fil[:,1] = rec_fil[:,1] + rec_fil[:,3]
    # get unique row positions
    rows_pos = np.sort(np.unique(rec_fil[:,1]))
    # filter noise
    rows_pos = find_row_corrdinates(rows_pos)
    
    return(rec_fil,rows_pos)

In [16]:
def pharse_string(string, dist, thresh_val):
    '''
    pharse string into usable variables based on the distance between the characters
    input:  string = '13,87000'
            dist = np.array([ 5, 17, 19,  7,  6, 20])
    output: mass = ['13,8', '700', '0']
    '''
    # list of variables
    mass = []
    # if comma is detected swich to 1
    comma = 0
    # temporary helper variable
    save = string[0]
    # loop over char in string
    for i, char in enumerate(string[1:]):
        # if char is comma -> add char and reuse dist on ith position
        if char == ',':
            save = save + char
            dist[i] = thresh_val - 1
            comma = 1
        # check if current dist is bigger than threshold -> add to list of variables
        else:
            if dist[i-comma] <= thresh_val:
                save = save + char
            else:
                mass.append(save)
                save = char
    # add last variable
    mass.append(save)
    
    return mass

In [22]:
string = '13,87000'
dist = np.array([ 5, 17, 19,  7,  6, 20])
pharse_string(string, dist, 17)

['13,8', '700', '0']

In [23]:
string = '14,510000'
dist = np.array([ 2, 11, 10,  3,  4,  3, 11])
pharse_string(string, dist, 10)

['14,51000', '0']

### try

In [17]:
# invert binary
img = cv2.bitwise_not(img_thresh)
# cut the mass
img = ocr.cut_feature(img, "mass")
# get boundries of detected characters
rects = ocr.find_objects(img)
# convert to numpy array
rects = np.asarray(rects)

In [28]:
rects

array([[ 869,  473,    9,   21],
       [1031,  439,   15,   61],
       [ 732,  439,    8,   43],
       [ 311,  439,    8,   43],
       [1285,  438,   39,   62],
       [1196,  438,   35,   45],
       [1146,  438,   39,   62],
       [1057,  438,   35,   45],
       [ 751,  438,   35,   45],
       [ 549,  438,   37,   44],
       [1627,  437,   36,   45],
       [1578,  437,   40,   47],
       [1534,  437,   36,   45],
       [1485,  437,   41,   47],
       [1397,  437,   38,   46],
       [1356,  437,   36,   47],
       [1242,  437,   36,   45],
       [1103,  437,   36,   45],
       [1010,  437,   22,   45],
       [ 962,  437,   40,   47],
       [ 797,  437,   59,   45],
       [ 686,  437,   36,   45],
       [ 640,  437,   36,   45],
       [ 591,  437,   40,   47],
       [ 503,  437,   40,   47],
       [ 374,  437,   40,   47],
       [ 348,  426,   20,   57],
       [ 325,  426,   20,   57],
       [1078,  423,    8,    9],
       [1065,  423,    7,    9],
       [14

In [19]:
info.count('nutz')

1

In [20]:
rects[:,3].max()/(rects[:,3].min()*1.5)

4.592592592592593

In [53]:
def find_row_corrdinates(rows_pos):
    rows = []
    temp = []
    x = rows_pos[0]
    for cor in rows_pos:
        if (cor < x * 1.1) & (cor > x * 0.9):
            temp.append(cor)
        else:
            rows.append(int(sum(temp) / len(temp)))
            x = cor
            temp = []
    rows.append(int(sum(temp) / len(temp)))
    return(np.array(rows))

In [38]:
# filter small points
rect_max_hight = rects[:,3].max()
rec_fil = rects[rect_max_hight/rects[:,3] < rect_max_hight/(rects[:,3].min()*1.5)]
# get lower coordinates
rec_fil[:,1] = rec_fil[:,1] + rec_fil[:,3]
# get unique row positions
rows_pos = np.sort(np.unique(rec_fil[:,1]))
# filter noise
rows_pos = find_row_corrdinates(rows_pos)

In [39]:
rows_pos

array([388, 490])

In [116]:
# filter only nutzungs row
rec_fil_fil = rec_fil[np.where((rec_fil[:,1] <= rows_pos[1]*1.05) & (rec_fil[:,1] >= rows_pos[1]*0.95))]

In [117]:
print(490*1.05)
print(490*0.95)
print('-----------------------')
print(388*1.05)
print(388*0.95)

514.5
465.5
-----------------------
407.40000000000003
368.59999999999997


In [118]:
rec_fil_fil

array([[1125,  324,    9,   21],
       [1984,  312,    8,   43],
       [1711,  312,    8,   43],
       [ 988,  312,    8,   43],
       [ 567,  312,    8,   43],
       [2000,  330,   39,   62],
       [1597,  330,   39,   62],
       [1507,  313,   35,   45],
       [1007,  313,   35,   45],
       [ 805,  312,   37,   44],
       [ 374,  330,   39,   62],
       [1885,  313,   42,   46],
       [1818,  312,   59,   45],
       [1727,  313,   38,   46],
       [1663,  314,   40,   47],
       [1554,  312,   36,   45],
       [1436,  314,   40,   47],
       [1345,  312,   36,   45],
       [1297,  313,   42,   46],
       [1232,  314,   40,   47],
       [1053,  312,   59,   45],
       [ 942,  312,   36,   45],
       [ 896,  312,   36,   45],
       [ 847,  314,   40,   47],
       [ 759,  314,   40,   47],
       [ 630,  314,   40,   47],
       [ 331,  312,   36,   45],
       [ 282,  313,   42,   46],
       [ 215,  312,   36,   45],
       [ 605,  313,   20,   57],
       [ 5

In [ ]:
for rect in rects:
    

In [30]:
# filter only nutzungs row
rec_fil_fil = rec_fil[np.where(rec_fil[:,1] == rows_pos[0])]

In [45]:
rec_fil[-1][1] + rec_fil[-1][1] * 0.15

287.5

In [47]:
# filter only nutzungs row
rec_fil_fil = rec_fil[np.where((rec_fil[:,1] <= rec_fil[-1][1] + rec_fil[-1][1] * 0.15) & (rec_fil[:,1] >= rec_fil[-1][1] - rec_fil[-1][1] * 0.15))]

In [48]:
rec_fil_fil

array([[824, 252,  40,  59],
       [777, 252,  41,  60],
       [638, 252,  41,  60],
       [574, 250,  22,  58],
       [430, 252,  40,  60],
       [384, 252,  39,  60],
       [314, 252,  40,  60],
       [707, 250,  42,  59],
       [500, 250,  40,  59],
       [244, 250,  42,  60],
       [184, 250,  49,  60]])

In [32]:
# sort
a = rec_fil_fil.copy()
a.view('i8,i8,i8,i8').sort(order=['f1'], axis=0)

In [33]:
a

array([[ 648,  475,   28,   39],
       [ 685,  475,   24,   39],
       [ 729,  475,   15,   39],
       [ 759,  475,   24,   40],
       [ 801,  475,   25,   40],
       [ 845,  475,   27,   39],
       [ 877,  475,   25,   40],
       [ 908,  475,   25,   40],
       [ 953,  475,   25,   40],
       [ 998,  475,   26,   40],
       [1043,  475,   24,   40],
       [1086,  475,   29,   39],
       [1133,  475,   24,   40],
       [1165,  475,   25,   39]])

In [36]:
a2 = a[2:-5]

In [87]:
pos_x = a2[:,0,].copy()

In [88]:
pos_x

array([729, 759, 801, 845, 877, 908, 953])

In [48]:
a2

array([[729, 475,  15,  39],
       [759, 475,  24,  40],
       [801, 475,  25,  40],
       [845, 475,  27,  39],
       [877, 475,  25,  40],
       [908, 475,  25,  40],
       [953, 475,  25,  40]])

In [59]:
for i in range(a2.shape[0]-1):
    print(a2[i+1,0] - (a2[i,0] + int(width_m)))

5
17
19
7
6
20


In [57]:
width_m = np.median(a2[:,2,])

In [58]:
width_m

25.0

In [89]:
diff = pos_x[1:] - (pos_x[:-1]+int(width_m))

In [90]:
diff

array([ 5, 17, 19,  7,  6, 20])

In [ ]:
def get_spaces(img_thresh): # public
        '''
            get spaces between maßnahmen code
        '''
        # invert binary
        img = cv2.bitwise_not(self.img_thresh)
        # cut the mass
        img = self.cut_feature(img, "mass")
        # get boundries of detected characters
        rects = self.find_objects(img)
        # convert to numpy array
        rects = np.asarray(rects)

### TODO dont filter commas

        # filter noise (small points)
        rec_fil = rects[rects[:,3] > np.mean(rects[:,3])/2]
        # get amount of Nutzungsmaßnahmen
        rec_fil[:,1] = rec_fil[:,1] + rec_fil[:,3]
        # get unique row positions
        rows_pos = np.sort(np.unique(rec_fil[:,1]))

        spaces = []

        for i in range(0, rows_pos.size-1, 2):
            # filter only nutzungs row
            rec_fil_fil = rec_fil[np.where(rec_fil[:,1] == rows_pos[i])]
            # invert array on first column
            rec_fil_fil.view('i8,i8,i8,i8').sort(order=['f1'], axis=0)
            # position of char on x-axis -> column 0
            pos_x = rec_fil_fil[:,0,].copy()
            # median width > column 2
            width_m = np.median(rec_fil_fil[:,2,])
            # space (pixels) between characters
            diff = pos_x[1:] - (pos_x[:-1]+int(width_m))
            # use otsu algorithm to obtain the best threshold value
            thresh_val = self.otsu(diff)

            diff[np.where(diff < thresh_val)] = 0
            diff[np.where(diff >= thresh_val)] = 1

            spaces.append(diff)

### TODO add possibitity for 2 or more Maßnahmen and one without text

        ## search for commas
        # get Maßnahme
        mass = self.get_text("mass")
        mass = mass.splitlines()
    ### TODO
        # find commas
        idx_comma = mass[0].find(',')
        # change space to no space
        spaces[0][idx_comma-1] = 0
        # add no space, since comma is not recognised as char
        spaces[0] = np.insert(spaces[0],3,0)

        return(spaces)


In [12]:
def from_string(ma_as_str, spaces):
    # split lines
    ma = ma_as_str.splitlines()
    nutz = ma[0].replace(" ", "")
    l = []
    ch = ""

    for i in range(len(nutz)):

        if i == 0:
            ch = nutz[i]
        elif i == len(nutz)-1:
            l.append(ch + nutz[i])
        elif spaces[0][i-1] == 0:
            ch = ch + nutz[i]
        elif spaces[0][i-1] == 1:
            l.append(ch)
            ch = nutz[i]
    l.append(ma[1])
    return l

In [17]:
from_string(ma, spaces)

['DF13,8700', '0', '2', '34', '35', 'El fördern u freistellen']

In [47]:
spaces

[array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])]

In [47]:
ma = 'DF4,7300023435\nEl Kronen freistellen'
spaces = [np.array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0])]
from_string(ma, spaces)

['DF', '4,7', '300', '0', '2', '3', '4', '35', 'El Kronen freistellen']

In [49]:
ma = 'DF47300023435\nEl Kronen freistellen'
spaces = [np.array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0])]
from_string(ma, spaces)

['DF', '473', '000', '2', '3', '4', '35', 'El Kronen freistellen']

In [50]:
# added 1 to spaces and ma
ma = 'DF4,73000213435\nEl Kronen freistellen'
spaces = [np.array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0])]
from_string(ma, spaces)

['DF', '4,7', '300', '0', '2', '1', '3', '4', '35', 'El Kronen freistellen']

In [51]:
# added 1 to spaces and ma
ma = 'DF213435\nEl Kronen freistellen'
spaces = [np.array([0, 1, 1, 1, 1, 1, 1, 1, 0])]
from_string(ma, spaces)

['DF', '2', '1', '3', '4', '35', 'El Kronen freistellen']

In [9]:
# split lines
ma = ma.splitlines()

In [10]:
ma

['DF4,7300023435', 'El Kronen freistellen']

In [44]:
l = []
ch = ""

for i in range(len(ma[0])):
    
    if i == 0:
        ch = ma[0][i]
    elif i == len(ma[0])-1:
        l.append(ch + ma[0][i])
    elif spaces[0][i-1] == 0:
        ch = ch + ma[0][i]
    elif spaces[0][i-1] == 1:
        l.append(ch)
        ch = ma[0][i]
l.append(ma[1])

In [45]:
l

['DF', '4,7', '300', '0', '2', '3', '4', '35', 'El Kronen freistellen']

## BZ

In [10]:
bz = "3BU 4FI 3AH"

In [11]:
bz = bz.split()

In [12]:
bz

['3BU', '4FI', '3AH']

In [13]:
bz[0][-2:]

'BU'

In [14]:
int(bz[0][:-2])

3

In [18]:
bzs = []
for b in bz:
    bzs.append([int(b[:-2]),b[-2:]])

In [20]:
# Return double of n 
def addition(n): 
    return n + n 
  
# We double all numbers using map() 
numbers = (1, 2, 3, 4) 
result = map(addition, numbers) 
print(list(result))

[2, 4, 6, 8]


In [21]:
bz

['3BU', '4FI', '3AH']

In [27]:
def spliter(n):
    return int(n[:-2]),n[-2:]
result = map(spliter, bz)

In [28]:
result

In [19]:
bzs

[[3, 'BU'], [4, 'FI'], [3, 'AH']]

In [1]:
from OCRData import BestZiel
from OCRData import BAZiel

In [2]:
ba1 = BAZiel(13, 'BU')
ba2 = BAZiel(4, 'K')
ba3 = BAZiel(3, 'LA')

In [3]:
bz = BestZiel([ba1, ba2, ba3])

In [8]:
bz = BestZiel.from_string('3BI 4KI 3FI')

3BI
3
BI
4KI
4
KI
3FI
3
FI


In [9]:
bz

BestZiel(bz=[BAZiel(part=3, ba='BI', error=False), BAZiel(part=4, ba='KI', error=False), BAZiel(part=3, ba='FI', error=False)], error=False)

In [10]:
bz.check_attr()

In [11]:
bz

BestZiel(bz=[BAZiel(part=3, ba='BI', error=False), BAZiel(part=4, ba='KI', error=False), BAZiel(part=3, ba='FI', error=False)], error=False)

In [6]:
from OCRData import Text

In [9]:
# get text
txt = ocr.get_text('text')

In [10]:
Text.from_string(txt)

Text(line0='ST im Süden breiter Rücken, am Rücken steinig mit STOE 71 und HD-Typ', line1='BE einige ES KB BU BI AH Kl, Elam Rücken, einige eingewachsene BU-El-Überhälter, ungleichaltrig +/- 10 Jahre, Ausschlagswald', line2='')

In [24]:
from OCRData import Nutz

In [46]:
nutz = Nutz(ma=l[0], v_lh=int(l[2]), v_nh=int(l[3]), dring=int(l[4]), behoerde=0, zeitp=int(l[5]), \
            schlaeg=int(l[6]), rueck=int(l[7]), text=l[8])

In [47]:
l

['DF', '4,7', '300', '0', '2', '3', '4', '35', 'El Kronen freistellen']

In [48]:
nutz

Nutz(ma='DF', area=0.0, v_lh=300, v_nh=0, dring=2, behoerde=0, zeitp=3, schlaeg=4, rueck=35, text='El Kronen freistellen', error=False)

In [49]:
nutz.check_attr()

In [50]:
nutz

Nutz(ma='DF', area=0.0, v_lh=300, v_nh=0, dring=2, behoerde=0, zeitp=3, schlaeg=4, rueck=35, text='El Kronen freistellen', error=True)